### PR TITLE
Complete Endpoints for Tournament/Match/MoranProcess & Database Storage

### PR DESCRIPTION
**Pull request by erik-sn**
This adds:

- CRUD operations for Tournament, Match & Moran Process. Includes starting, saving game & results in the database
- Results serialization and return to client
- 99% code coverage
- Travis CI & coverage builds
- External volume in docker so the `db` service can be deleted/removed/rebuilt without loss of data

These operations are all synchronous, so no Celery implementation (yet). For most use cases this seems to be ok, possibly even preferable, but large Tournaments will probably run sufficiently long to require an asynchronous solution.

The way I implemented this was to use abstract classes that I called a `Game`. Where a `Game` is inherited by Tournament/Match/MP. This pattern is followed for the views, serializers & definitions. This allows for extensibility if new types of "Games" are added.

Flow of operations is roughly:

1. Client POSTs to the view
2. POST data contains all parameters required to start a game - this is de-serialized into the `Definition`
3. Model class is passed this definition and runs the axelrod tournament/match/mp
4. Results are serialized into JSON and saved in a JSON database field
5. Entire game & its results are returned to the client

I will say that I am not completely up to date on which parts of the results are most desirable or needed, there are a few fields I have not implemented yet.

These games & their results are then accessible through GET requests. DELETE requests are functional but only available to authenticated users with `is_staff` set.

### CODE REVIEW

**Comment by erik-sn** [comment]
also note that this is only taking in strategy_ids and using default Strategy parameters - still have to implement accepting custom Strategy parameters.

**Comment by meatballs** [comment]
Wow! There's a lot of work in here!

I'm not likely to have the time to look at this for a few days - real life has a nasty habit of getting in the way sometimes.

**Comment by meatballs** [comment]
First glance through and this looks good. My only comment at the moment is the use of the title 'Game'

Given that we have a classes in the library called 'Game', 'Tournament' and 'Match', I think we should only use those here where they mean the same thing. Tournament and Match are ok, but I think we need to use a different term for Name.

**Comment by erik-sn** [comment]
I'm struggling to think of a good name - does anything come to mind? Tournament, Match and MP are all types of...

**Comment by drvinceknight** [comment]
> I'm struggling to think of a good name - does anything come to mind? Tournament, Match and MP are all types of...

Perhaps "Contest"?

**Comment by erik-sn** [comment]
Ok sounds good - can we close this pull request and I will submit another with "Contest"? Any thing else that needs to be changed/looked at?

**Comment by meatballs** [comment]
No need to close it. You can just make changes and push them.

**Pull request merged**
